### Script used to clean and Sort data

In [1]:
# Use this cell to set up import statements for all of the packages 
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

# 'magic word' so that your visualizations are plotted
%matplotlib inline

In [2]:
nics_df = pd.read_csv('nics.csv')
nics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 8 columns):
month       6000 non-null object
state       6000 non-null object
permit      6000 non-null int64
handgun     6000 non-null int64
long_gun    6000 non-null int64
other       6000 non-null int64
multiple    6000 non-null int64
totals      6000 non-null int64
dtypes: int64(6), object(2)
memory usage: 375.1+ KB

In [3]:
# convert object data type to python datetime
nics_df['month'] = pd.to_datetime(nics_df['month'])
# create anew year column
nics_df['year'] = nics_df['month'].dt.year

In [5]:
census_df = pd.read_csv('census.csv')

### create pandas dataset July 1, 2016 or April 1, 2010 with fire background check and census data

In [6]:
#greater than the start date and smaller than the end date
mask_2010 = (nics_df['month'] >= '2010-01-01') & (nics_df['month'] <= '2010-04-01')
mask_2016 = (nics_df['month'] >= '2016-01-01') & (nics_df['month'] <= '2016-07-01')
nics_2010_df = nics_df.loc[mask_2016].groupby(['state' ,'year']).sum().reset_index().sort_values('state')
nics_2016_df = nics_df.loc[mask_2016].groupby(['state' ,'year']).sum().reset_index().sort_values('state')

## sorting datae old and new columns

In [7]:
census_2010_list_float = ['Persons under 5 years, percent, April 1, 2010',
                          'Persons under 18 years, percent, April 1, 2010',
                          'Persons 65 years and over, percent, April 1, 2010',
                          'Female persons, percent, April 1, 2010'
                        ]

In [8]:
census_2016_list_float = ['Persons under 5 years, percent, July 1, 2016,  (V2016)', 
                          'Persons under 18 years, percent, July 1, 2016,  (V2016)',
                          'Persons 65 years and over, percent,  July 1, 2016,  (V2016)',
                          'Female persons, percent,  July 1, 2016,  (V2016)',                              
                         ]

In [9]:
census_2010_2016_list_float = ['Persons under 5 years, percent', 'Persons under 18 years, percent',
                              'Persons 65 years and over, percent',
                              'Female persons, percent',                              
                                ]

In [10]:
census_2010_list_int = ['Population estimates base, April 1, 2010,  (V2016)', 'Housing units, April 1, 2010']

In [11]:
census_2016_list_int = ['Population estimates, July 1, 2016,  (V2016)', 'Housing units,  July 1, 2016,  (V2016)']

In [12]:
census_2010_2016_list_int = ['Population estimates', 'Housing units']

## Usfual Functions

In [13]:
def to_float(df, col):
    '''
    input data frame name , column name
    return float type
    '''
    df1 = df[col].astype(str).str.strip().replace(',','')
    for i in range(df.shape[0]):
        if ((type(df1[i]) != float) and (df1[i] != np.nan)):
            if (df1.str.contains("%")[i]):            
                df1[i] = float(df1[i].replace('%',''))/100   
            else :
                df1[i] = df1[i].replace('$','')
                df1[i] = float(df1[i].replace(',',''))
    return df1

In [14]:
def to_int(df, col):
    '''
    input data frame name , column name
    return int type
    '''
    df1 = df[col].astype(str).str.strip().replace(',','')
    for i in range(df.shape[0]):
        if ((type(df1[i]) != int) and (df1[i] != np.nan)):
            if (df1.str.contains(".")[i]):
                index  = df1[i].find('.')
                df1[i] = df1[i][:-(len(df1[i])-index)]
                df1[i] = df1[i].replace('.','')
                if(df1[i] == ''):
                    df1[i] = 0  
            else :
                df1[i] = df1[i].replace('$','')
                df1[i] = int(df1[i].replace(',',''))
    return df1

### build anew data set

In [15]:
for i in range(len(census_2010_list_float)):
    nics_2010_df[census_2010_2016_list_float[i]] = to_float(census_df, census_2010_list_float[i])

In [16]:
for i in range(len(census_2016_list_float)):
    nics_2016_df[census_2010_2016_list_float[i]] = to_float(census_df, census_2016_list_float[i])

In [17]:
for i in range(len(census_2010_list_int)):
    nics_2010_df[census_2010_2016_list_int[i]] = to_int(census_df, census_2010_list_int[i])

In [18]:
for i in range(len(census_2016_list_int)):
    nics_2016_df[census_2010_2016_list_int[i]] = to_int(census_df, census_2016_list_int[i])

In [19]:
# Stack the DataFrames on top of each other
nics_2010_2016_df = pd.concat([nics_2016_df, nics_2010_df], axis=0, sort=True)

In [19]:
nics_2010_2016_df

,"Female persons, percent",Housing units,"Persons 65 years and over, percent","Persons under 18 years, percent","Persons under 5 years, percent",Population estimates,handgun,long_gun,multiple,other,permit,state,totals,year
0,0.516,2230185,0.161,0.226,0.06,4863300,106051,65852,4228,4266,173435,Alabama,377414,2016
1,0.477,310658,0.104,0.252,0.073,741894,20723,18611,1219,1620,1788,Alaska,46903,2016
2,0.503,2961003,0.169,0.235,0.063,6931071,97667,56275,4439,7260,45008,Arizona,230724,2016
3,0.509,1354762,0.163,0.236,0.064,2988248,47751,36194,2536,1767,36112,Arkansas,145960,2016
4,0.503,14060525,0.136,0.232,0.063,39250017,311432,237872,0,57685,723586,California,1338152,2016
5,0.497,2339118,0.134,0.228,0.061,5540545,136696,93561,7771,8756,56043,Colorado,304322,2016
6,0.512,1499116,0.161,0.211,0.052,3576452,85582,28291,0,1709,108659,Connecticut,224288,2016
7,0.516,426149,0.175,0.215,0.058,952065,14904,10476,540,727,5546,Delaware,33197,2016
8,0.511,9301642,0.199,0.201,0.055,20612439,384397,167826,13776,24436,207639,Florida,826773,2016
9,0.513,4218776,0.131,0.244,0.064,10310371,114230,57690,4141,3716,147135,Georgia,351694,2016
10,0.498,537114,0.171,0.216,0.064,1428557,0,0,0,0,10338,Hawaii,10364,2016
11,0.499,700825,0.151,0.26,0.068,1683140,26110,27111,1358,1592,24594,Idaho,86938,2016
12,0.509,5326970,0.146,0.229,0.06,12801539,179261,83869,6070,0,863508,Illinois,1141677,2016
13,0.507,2854546,0.149,0.238,0.064,6633053,165322,88329,5198,10443,759753,Indiana,1033411,2016
14,0.503,1380162,0.164,0.233,0.064,3134693,1443,16724,32,260,106656,Iowa,126127,2016
15,0.502,1259864,0.15,0.246,0.067,2907289,48069,35595,2374,3027,9963,Kansas,106143,2016
16,0.507,1965556,0.156,0.228,0.062,4436974,82693,52031,4076,2294,2075886,Kentucky,2241872,2016
17,0.511,2036975,0.144,0.238,0.066,4681666,100680,59978,4544,6708,16697,Louisiana,203205,2016
18,0.51,730705,0.194,0.191,0.049,1331479,28614,21295,1170,1647,4169,Maine,58840,2016
19,0.516,2447127,0.146,0.224,0.061,6016447,29869,36190,191,954,21838,Maryland,90660,2016
20,0.515,2858026,0.158,0.202,0.053,6811779,44210,23459,1548,5343,54482,Massachusetts,129670,2016
21,0.508,4560055,0.162,0.221,0.058,9928300,100810,62553,1513,3623,162800,Michigan,343679,2016
22,0.502,2409935,0.151,0.233,0.064,5519952,78860,68445,2871,6039,186992,Minnesota,347816,2016
23,0.515,1307441,0.151,0.241,0.063,2988726,70839,38110,2823,2321,11659,Mississippi,143468,2016
24,0.509,2760084,0.161,0.228,0.061,6093000,163069,97545,7124,10050,78155,Missouri,375259,2016
25,0.497,497756,0.177,0.218,0.06,1042520,22013,28876,1505,1203,13122,Montana,76091,2016
26,0.502,827156,0.15,0.248,0.07,1907116,859,12343,50,149,36030,Nebraska,50449,2016
27,0.499,1221698,0.15,0.23,0.063,2940058,38466,20254,1952,1864,19771,Nevada,85647,2016
28,0.505,625307,0.17,0.195,0.048,1334795,39821,23775,34,1162,29551,New Hampshire,95190,2016
29,0.512,3604409,0.153,0.222,0.058,8944469,43276,26007,0,1464,0,New Jersey,70747,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,0.516,2808254,0.138,0.217,0.056,6547813,44210,23459,1548,5343,54482,Massachusetts,129670,2016
21,0.509,4532233,0.138,0.237,0.06,9884129,100810,62553,1513,3623,162800,Michigan,343679,2016
22,0.504,2347201,0.129,0.242,0.067,5303924,78860,68445,2871,6039,186992,Minnesota,347816,2016
23,0.514,1274719,0.128,0.255,0.071,2968103,70839,38110,2823,2321,11659,Mississippi,143468,2016
24,0.51,2712729,0.14,0.238,0.065,5988928,163069,97545,7124,10050,78155,Missouri,375259,2016
25,0.498,482825,0.148,0.226,0.063,989414,22013,28876,1505,1203,13122,Montana,76091,2016
26,0.504,796793,0.135,0.251,0.072,1826334,859,12343,50,149,36030,Nebraska,50449,2016
27,0.495,1173814,0.12,0.246,0.069,2700691,38466,20254,1952,1864,19771,Nevada,85647,2016
28,0.507,614754,0.135,0.218,0.053,1316461,39821,23775,34,1162,29551,New Hampshire,95190,2016
29,0.513,3553562,0.135,0.235,0.062,8791953,43276,26007,0,1464,0,New Jersey,70747,2016
30,0.506,901388,0.132,0.252,0.07,2059198,40385,29154,2156,2813,9100,New Mexico,91285,2016
31,0.516,8108103,0.135,0.223,0.06,19378110,78818,96680,1356,7264,31037,New York,219157,2016
32,0.513,4327528,0.129,0.239,0.066,9535688,9094,83170,1623,5521,206390,North Carolina,334300,2016
33,0.495,317498,0.145,0.223,0.066,672591,12118,17107,527,756,8620,North Dakota,40654,2016
34,0.512,5127508,0.141,0.237,0.062,11536727,235119,124455,9306,14348,105483,Ohio,505508,2016
35,0.505,1664378,0.135,0.248,0.07,3751615,99764,62987,6054,7703,0,Oklahoma,201571,2016
36,0.505,1675562,0.139,0.226,0.062,3831072,102037,74677,0,0,323,Oregon,177053,2016
37,0.513,5567315,0.154,0.22,0.057,12702857,362732,78346,0,92,190694,Pennsylvania,636758,2016
38,0.517,463388,0.144,0.213,0.055,1052940,8476,5699,1061,459,0,Rhode Island,15968,2016
39,0.514,2137683,0.137,0.234,0.065,4625410,77211,39293,2429,3778,92424,South Carolina,228066,2016
40,0.5,363438,0.143,0.249,0.073,814195,21495,23633,1201,1713,9317,South Dakota,59733,2016
41,0.513,2812133,0.134,0.236,0.064,6346298,185750,103356,8687,0,40164,Tennessee,398999,2016
42,0.504,9977436,0.103,0.273,0.077,25146100,382857,229184,18450,23290,253124,Texas,986866,2016
43,0.498,979709,0.09,0.315,0.095,2763888,26318,25309,1191,1899,113799,Utah,174063,2016
44,0.507,322539,0.146,0.207,0.051,625741,11189,9784,511,780,0,Vermont,22314,2016
45,0.509,3364939,0.122,0.232,0.064,8001041,168077,102611,0,6740,5581,Virginia,283050,2016
46,0.502,2885677,0.123,0.235,0.065,6724545,123792,77827,4479,13065,198516,Washington,445314,2016
47,0.507,881917,0.16,0.209,0.056,1853011,53672,38828,3089,2120,17984,West Virginia,134301,2016
48,0.504,2624358,0.137,0.236,0.063,5687289,108650,80866,324,5820,64029,Wisconsin,262844,2016
49,0.49,261868,0.124,0.24,0.071,563767,12981,13547,741,889,4969,Wyoming,35611,2016

In [20]:
# save file for future process
nics_2010_2016_df.to_csv('census_2010_2016.csv', index = False)

### July 1, 2016 only

In [21]:
# float 2016 only
census_July_2016_list_float = ['White alone, percent, July 1, 2016,  (V2016)',
                               'Black or African American alone, percent, July 1, 2016,  (V2016)',
                               'American Indian and Alaska Native alone, percent, July 1, 2016,  (V2016)',
                               'Asian alone, percent, July 1, 2016,  (V2016)',
                               'Native Hawaiian and Other Pacific Islander alone, percent, July 1, 2016,  (V2016)',
                               'Two or More Races, percent, July 1, 2016,  (V2016)',
                               'Hispanic or Latino, percent, July 1, 2016,  (V2016)',
                               'White alone, not Hispanic or Latino, percent, July 1, 2016,  (V2016)'
                              ]

In [22]:
census_July_2016_list_float_new = ['White alone, percent', 'Black or African American alone, percent',
                               'American Indian and Alaska Native alone, percent',
                               'Asian alone, percent',
                               'Native Hawaiian and Other Pacific Islander alone, percent',
                               'Two or More Races, percent',
                               'Hispanic or Latino, percent',
                               'White alone, not Hispanic or Latino, percent'
                              ]

In [23]:
#greater than the start date and smaller than the end date
mask = (nics_df['month'] >= '2016-01-01') & (nics_df['month'] <= '2016-07-01')
nics_July_2016_df = nics_df.loc[mask].groupby(['state' ,'year']).sum().reset_index().sort_values('state')

In [24]:
for i in range(len(census_July_2016_list_float)):
    nics_July_2016_df[census_July_2016_list_float_new[i]] = to_float(census_df, census_July_2016_list_float[i])

In [25]:
nics_July_2016_df

,state,year,permit,handgun,long_gun,other,multiple,totals,"White alone, percent","Black or African American alone, percent","American Indian and Alaska Native alone, percent","Asian alone, percent","Native Hawaiian and Other Pacific Islander alone, percent","Two or More Races, percent","Hispanic or Latino, percent","White alone, not Hispanic or Latino, percent"
0,Alabama,2016,173435,106051,65852,4266,4228,377414,0.693,0.268,0.007,0.014,0.001,0.016,0.042,0.658
1,Alaska,2016,1788,20723,18611,1620,1219,46903,0.661,0.038,0.152,0.063,0.013,0.073,0.07,0.612
2,Arizona,2016,45008,97667,56275,7260,4439,230724,0.833,0.049,0.054,0.034,0.003,0.028,0.309,0.555
3,Arkansas,2016,36112,47751,36194,1767,2536,145960,0.794,0.157,0.01,0.016,0.003,0.02,0.073,0.729
4,California,2016,723586,311432,237872,57685,0,1338152,0.727,0.065,0.017,0.148,0.005,0.038,0.389,0.377
5,Colorado,2016,56043,136696,93561,8756,7771,304322,0.875,0.045,0.016,0.033,0.002,0.03,0.213,0.686
6,Connecticut,2016,108659,85582,28291,1709,0,224288,0.806,0.118,0.005,0.047,0.001,0.023,0.157,0.677
7,Delaware,2016,5546,14904,10476,727,540,33197,0.701,0.226,0.006,0.04,0.001,0.026,0.092,0.629
8,Florida,2016,207639,384397,167826,24436,13776,826773,0.776,0.168,0.005,0.029,0.001,0.021,0.249,0.549
9,Georgia,2016,147135,114230,57690,3716,4141,351694,0.612,0.32,0.005,0.041,0.001,0.021,0.094,0.534
10,Hawaii,2016,10338,0,0,0,0,10364,0.258,0.022,0.004,0.377,0.102,0.237,0.104,0.221
11,Idaho,2016,24594,26110,27111,1592,1358,86938,0.933,0.008,0.018,0.015,0.002,0.024,0.123,0.824
12,Illinois,2016,863508,179261,83869,0,6070,1141677,0.772,0.147,0.006,0.055,0.001,0.019,0.17,0.617
13,Indiana,2016,759753,165322,88329,10443,5198,1033411,0.856,0.097,0.004,0.022,0.001,0.02,0.068,0.796
14,Iowa,2016,106656,1443,16724,260,32,126127,0.914,0.037,0.005,0.025,0.001,0.018,0.058,0.862
15,Kansas,2016,9963,48069,35595,3027,2374,106143,0.866,0.062,0.012,0.03,0.001,0.029,0.116,0.763
16,Kentucky,2016,2075886,82693,52031,2294,4076,2241872,0.88,0.083,0.003,0.015,0.001,0.019,0.035,0.85
17,Louisiana,2016,16697,100680,59978,6708,4544,203205,0.632,0.326,0.008,0.018,0.001,0.016,0.05,0.59
18,Maine,2016,4169,28614,21295,1647,1170,58840,0.948,0.015,0.007,0.012,NaN,0.017,0.016,0.935
19,Maryland,2016,21838,29869,36190,954,191,90660,0.593,0.307,0.006,0.066,0.001,0.028,0.098,0.515
20,Massachusetts,2016,54482,44210,23459,5343,1548,129670,0.818,0.086,0.005,0.067,0.001,0.023,0.115,0.73
21,Michigan,2016,162800,100810,62553,3623,1513,343679,0.796,0.142,0.007,0.031,NaN,0.024,0.05,0.754
22,Minnesota,2016,186992,78860,68445,6039,2871,347816,0.85,0.062,0.013,0.049,0.001,0.024,0.052,0.806
23,Mississippi,2016,11659,70839,38110,2321,2823,143468,0.593,0.377,0.006,0.011,0.001,0.012,0.031,0.569
24,Missouri,2016,78155,163069,97545,10050,7124,375259,0.832,0.118,0.006,0.02,0.001,0.022,0.041,0.797
25,Montana,2016,13122,22013,28876,1203,1505,76091,0.892,0.006,0.066,0.008,0.001,0.027,0.036,0.865
26,Nebraska,2016,36030,859,12343,149,50,50449,0.889,0.05,0.014,0.025,0.001,0.021,0.107,0.796
27,Nevada,2016,19771,38466,20254,1864,1952,85647,0.751,0.096,0.016,0.087,0.008,0.042,0.285,0.499
28,New Hampshire,2016,29551,39821,23775,1162,34,95190,0.938,0.015,0.003,0.027,0.001,0.017,0.035,0.908
29,New Jersey,2016,0,43276,26007,1464,0,70747,0.724,0.15,0.006,0.098,0.001,0.022,0.2,0.558
30,New Mexico,2016,9100,40385,29154,2813,2156,91285,0.826,0.025,0.106,0.017,0.002,0.025,0.485,0.381
31,New York,2016,31037,78818,96680,7264,1356,219157,0.699,0.177,0.01,0.089,0.001,0.025,0.19,0.558
32,North Carolina,2016,206390,9094,83170,5521,1623,334300,0.71,0.222,0.016,0.029,0.001,0.022,0.092,0.635
33,North Dakota,2016,8620,12118,17107,756,527,40654,0.879,0.029,0.055,0.015,0.001,0.021,0.036,0.85
34,Ohio,2016,105483,235119,124455,14348,9306,505508,0.825,0.128,0.003,0.022,0.001,0.022,0.037,0.795
35,Oklahoma,2016,0,99764,62987,7703,6054,201571,0.746,0.078,0.092,0.022,0.002,0.061,0.103,0.662
36,Oregon,2016,323,102037,74677,0,0,177053,0.874,0.021,0.018,0.045,0.004,0.038,0.128,0.764
37,Pennsylvania,2016,190694,362732,78346,92,0,636758,0.824,0.118,0.004,0.035,0.001,0.019,0.07,0.77
38,Rhode Island,2016,0,8476,5699,459,1061,15968,0.844,0.081,0.01,0.036,0.002,0.027,0.149,0.733
39,South Carolina,2016,92424,77211,39293,3778,2429,228066,0.685,0.275,0.005,0.016,0.001,0.018,0.055,0.639
40,South Dakota,2016,9317,21495,23633,1713,1201,59733,0.852,0.02,0.09,0.015,0.001,0.023,0.037,0.825
41,Tennessee,2016,40164,185750,103356,0,8687,398999,0.787,0.171,0.004,0.018,0.001,0.019,0.052,0.742
42,Texas,2016,253124,382857,229184,23290,18450,986866,0.794,0.126,0.01,0.048,0.001,0.019,0.391,0.426
43,Utah,2016,113799,26318,25309,1899,1191,174063,0.911,0.014,0.016,0.025,0.01,0.025,0.138,0.788
44,Vermont,2016,0,11189,9784,780,511,22314,0.946,0.013,0.004,0.018,NaN,0.019,0.019,0.931
45,Virginia,2016,5581,168077,102611,6740,0,283050,0.7,0.198,0.005,0.066,0.001,0.029,0.091,0.624
46,Washington,2016,198516,123792,77827,13065,4479,445314,0.8,0.041,0.019,0.086,0.008,0.046,0.124,0.695
47,West Virginia,2016,17984,53672,38828,2120,3089,134301,0.936,0.036,0.002,0.008,NaN,0.017,0.015,0.923
48,Wisconsin,2016,64029,108650,80866,5820,324,262844,0.875,0.066,0.011,0.028,0.001,0.019,0.067,0.817
49,Wyoming,2016,4969,12981,13547,889,741,35611,0.928,0.013,0.027,0.01,0.001,0.021,0.1,0.841

In [25]:
nics_July_2016_df.to_csv('_$census_July_2016.csv', index = False)

## 2014_2015

In [26]:
census_2014_2015_list_float = ['Total employment, percent change, 2014-2015']

In [27]:
census_list_float = ['Total employment, percent change']

In [28]:
#greater than the start date and smaller than the end date
mask_2014 = (nics_df['month'] >= '2014-01-01') & (nics_df['month'] <= '2014-12-01')
mask_2015 = (nics_df['month'] >= '2015-01-01') & (nics_df['month'] <= '2015-12-01')
nics_2014_df = nics_df.loc[mask_2014].groupby(['state' ,'year']).sum().reset_index().sort_values('state')
nics_2015_df = nics_df.loc[mask_2015].groupby(['state' ,'year']).sum().reset_index().sort_values('state')

In [30]:
for i in range(len(census_list_float)):
    nics_2014_df[census_list_float[i]] = to_float(census_df, census_2014_2015_list_float[i])

In [31]:
for i in range(len(census_list_float)):
    nics_2015_df[census_list_float[i]] = to_float(census_df, census_2014_2015_list_float[i])

In [32]:
# Stack the DataFrames on top of each other
nics_2015_2015_df = pd.concat([nics_2014_df, nics_2015_df], axis=0, sort=True)

In [33]:
# save file for future process
nics_2015_2015_df.to_csv('_$census_2014_2015.csv', index = False)

### 2016

In [34]:
census_2016_list_int = ['Building permits, 2016']

In [35]:
census_2016_list_int_n = ['Building permits']

In [36]:
#greater than the start date and smaller than the end date
mask = (nics_df['month'] >= '2016-01-01') & (nics_df['month'] <= '2016-12-01')
nics_2016_df = nics_df.loc[mask].groupby(['state' ,'year']).sum().reset_index().sort_values('state')

In [37]:
for i in range(len(census_2016_list_int)):
    nics_2016_df[census_2016_list_int_n[i]] = to_int(census_df, census_2016_list_int[i])

In [38]:
nics_2016_df.to_csv('census_2016.csv', index = False)

### 2012

In [39]:
# only 2012 dollar
census_2012_list_int =['Total accommodation and food services sales, 2012 ($1,000)',
                       'Total health care and social assistance receipts/revenue, 2012 ($1,000)',
                       'Total manufacturers shipments, 2012 ($1,000)',
                       'Total merchant wholesaler sales, 2012 ($1,000)',
                       'Total retail sales, 2012 ($1,000)',
                       'Total retail sales per capita, 2012',
                       'All firms, 2012','Men-owned firms, 2012',
                       'Women-owned firms, 2012',
                       'Minority-owned firms, 2012',
                       'Nonminority-owned firms, 2012',
                       'Veteran-owned firms, 2012',
                       'Nonveteran-owned firms, 2012'    
                    ]

In [40]:
census_2012_list_int_n =['Total accommodation and food services sales',
                       'Total health care and social assistance receipts/revenue',
                       'Total manufacturers shipments',
                       'Total merchant wholesaler sales',
                       'Total retail sales',
                       'Total retail sales per capita',
                       'All firms','Men-owned firms',
                       'Women-owned firms',
                       'Minority-owned firms',
                       'Nonminority-owned firms',
                       'Veteran-owned firms',
                       'Nonveteran-owned firms'    
                    ]

In [41]:
#greater than the start date and smaller than the end date
mask = (nics_df['month'] >= '2012-01-01') & (nics_df['month'] <= '2012-12-01')
nics_2012_df = nics_df.loc[mask].groupby(['state' ,'year']).sum().reset_index().sort_values('state')

In [42]:
for i in range(len(census_2012_list_int)):
    nics_2012_df[census_2012_list_int_n[i]] = to_int(census_df, census_2012_list_int[i])

In [43]:
nics_2012_df.to_csv('census_2012.csv', index = False)

### 2011-2015

In [44]:
# int data 2011-2015
census_2011_2015_list_int = ['Households, 2011-2015','Median selected monthly owner costs -with a mortgage, 2011-2015',
                             'Median selected monthly owner costs -without a mortgage, 2011-2015',
                             'Median gross rent, 2011-2015','Persons per household, 2011-2015',
                             'Foreign born persons, percent, 2011-2015','Veterans, 2011-2015',
                             'Mean travel time to work (minutes), workers age 16 years+, 2011-2015',
                             'Median household income (in 2015 dollars), 2011-2015',
                             'Per capita income in past 12 months (in 2015 dollars), 2011-2015'    
                            ]

In [45]:
# float data 2011-2015
census_2011_2015_list_float = ['Owner-occupied housing unit rate, 2011-2015',
                              'Living in same house 1 year ago, percent of persons age 1 year+, 2011-2015',
                               'Language other than English spoken at home, percent of persons age 5 years+, 2011-2015',
                               'High school graduate or higher, percent of persons age 25 years+, 2011-2015',
                               'Bachelor\'s degree or higher, percent of persons age 25 years+, 2011-2015',
                               'With a disability, under age 65 years, percent, 2011-2015',
                               'In civilian labor force, total, percent of population age 16 years+, 2011-2015',
                               'In civilian labor force, female, percent of population age 16 years+, 2011-2015',
                               'Persons  without health insurance, under age 65 years, percent',
                               'Median value of owner-occupied housing units, 2011-2015','Persons in poverty, percent'                          
                              ]

In [46]:
#greater than the start date and smaller than the end date
mask_2014 = (nics_df['month'] >= '2014-01-01') & (nics_df['month'] <= '2014-12-01')
mask_2015 = (nics_df['month'] >= '2015-01-01') & (nics_df['month'] <= '2015-12-01')
nics_2014_df = nics_df.loc[mask_2014].groupby(['state' ,'year']).sum().reset_index().sort_values('state')
nics_2015_df = nics_df.loc[mask_2015].groupby(['state' ,'year']).sum().reset_index().sort_values('state')

In [47]:
for i in range(len(census_list_float)):
    nics_2014_df[census_list_float[i]] = to_float(census_df, census_2014_2015_list_float[i])

In [48]:
for i in range(len(census_list_float)):
    nics_2015_df[census_list_float[i]] = to_float(census_df, census_2014_2015_list_float[i])

In [49]:
# Stack the DataFrames on top of each other
nics_2015_2015_df = pd.concat([nics_2014_df, nics_2015_df], axis=0, sort=True)

In [50]:
# save file for future process
nics_2015_2015_df.to_csv('census_2014_2015.csv', index = False)

### 2015

In [51]:
# int 2015 
census_2015_list_int = ['Total employer establishments, 2015', 'Total employment, 2015',
                        'Total annual payroll, 2015 ($1,000)','Total nonemployer establishments, 2015'
                        ]

In [52]:
# int 2015 
census_2015_list_int_n = ['Total employer establishments', 'Total employment',
                        'Total annual payroll','Total nonemployer establishments'
                        ]

In [53]:
#greater than the start date and smaller than the end date
mask = (nics_df['month'] >= '2015-01-01') & (nics_df['month'] <= '2015-12-01')
nics_2012_df = nics_df.loc[mask].groupby(['state' ,'year']).sum().reset_index().sort_values('state')

In [54]:
for i in range(len(census_2015_list_int)):
    nics_2015_df[census_2015_list_int_n[i]] = to_int(census_df, census_2015_list_int[i])

In [56]:
nics_2015_df.to_csv('census_2015.csv', index = False)